controllers/JournalController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use Yii;
use app\models\Record;
use app\models\search\Record as JournalSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * JournalController implements the CRUD actions for Journal model.
 */
class JournalController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['index', 'view']
            ],

            'cache' => [
                'class' => 'yii\filters\HttpCache',
                'cacheControlHeader' => 'must-revalidate, private',
                'enabled' => false,
                'only' => ['index'],
                'lastModified' => function ($action, $params) {
                    $query = Record::find();
                    if (isset($params['user'])) {
                        $query->where(['user_name' => $params['user']]);
                    }
                    return strtotime($query->max('time'));
                },
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new JournalSearch();

        $params = Yii::$app->request->queryParams;
        if (!Yii::$app->user->identity->isManager()) {
            if (empty($params['user'])) {
                return $this->redirect(['index', 'user' => Yii::$app->user->identity->name]);
            }
            elseif (!Yii::$app->user->identity->isManager() && $params['user'] != Yii::$app->user->identity->name) {
                throw new ForbiddenHttpException('Forbidden');
            }
        }
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionObject($id) {
        $query = Record::find()->where(['object_id' => $id]);
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => $query,
                'sort' => [
                    'defaultOrder' => ['time' => SORT_DESC]
                ]
            ])
        ]);

    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Journal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Record the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Record::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/journal/index.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\models\Record;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\Record */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Journal');
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="journal-index">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'attribute' => 'type',
                'format' => 'html',
                'value' => function(Record $record) {
                    return Yii::t('app', $record->type);
                }
            ],
            [
                'attribute' => 'event',
                'format' => 'html',
                'value' => function(Record $record) {
                    return Html::a(Yii::t('app', $record->event), ['journal/view', 'id' => $record->id]);
                }
            ],
            [
                'attribute' => 'object_id',
                'format' => 'html',
                'value' => function(Record $record) {
                    $object = $record->getObject();
                    if ($object) {
                        return Html::a($object, method_exists($object, 'url')
                            ? $object->url()
                            : [$record->type . '/view', 'id' => $object->id]);
                    }
                    else {
                        return Yii::t('app', 'Not exists');
                    }
                }
            ],
            [
                'attribute' => 'user_name',
                'format' => 'html',
                'value' => function(Record $record) {
                    return Html::a($record->user_name, ['/user/view', 'name' => $record->user_name]);
                }
            ],
            [
                'attribute' => 'data',
                'format' => 'html',
                'value' => function(Record $record) {
                    $view = $record->getView();
                    if ($view) {
                        return $view;
                    }
                    else {
                        return $record->data ? json_encode($record->info) : '';
                    }
                }
            ],
            'time:datetime',
            'ip',
        ],
    ]); ?>

</div>

views/journal/object.php
<?php
/**
 * @var \yii\data\ActiveDataProvider $dataProvider
 */
use app\models\Record;
use yii\grid\GridView;
use yii\helpers\Html;

?>
<div class="journal-object">
    <h1>История изменений</h1>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'attribute' => 'event',
                'format' => 'html',
                'value' => function(Record $record) {
                    return Html::a(Yii::t('app', $record->event), ['/journal/view', 'id' => $record->id]);
                }
            ],
            'user_name',
            [
                'attribute' => 'data',
                'format' => 'html',
                'value' => function(Record $record) {
                    $view = $record->getView();
                    if ($view) {
                        return $view;
                    }
                    else {
                        return $record->data ? json_encode($record->info) : '';
                    }
                }
            ],
            [
                'attribute' => 'time',
                'format' => 'datetime',
                'contentOptions' => [
                    'class' => 'moment'
                ]
            ],
            'ip'
        ]
    ]) ?>
</div>

views/journal/view.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Record */

$event = Yii::t('app', $model->event);
$this->title = "$model->type $event";
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Journal'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="journal-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'type',
            [
                'attribute' => 'event',
                'format' => 'html',
                'value' => $event
            ],
            'object_id',
            'user_name',
            'time',
            'ip',
        ]
    ]) ?>

    <?php
    if ($model->data) {
        $data = unserialize($model->data);
        echo '<pre>' . json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . '</pre>';
    }

    ?>

</div>