models/User.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\models;


use app\behaviors\Journal;
use Exception;
use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\web\User as WebUser;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * Class User
 * @property integer id
 * @property string name
 * @property string auth
 * @property string email
 * @property string code
 * @property string hash
 * @property string perfect
 * @property string repeat
 * @property integer status
 * @property number account
 * @property integer last_access
 * @property integer ref_name
 * @property string vip
 * @property resource data
 * @property array bundle
 *
 * @property User referral
 * @package app\models
 */
class User extends ActiveRecord implements IdentityInterface {

    const BLOCKED = 0;
    const ADMIN = 1;
    const PLAIN = 2;
    const MANAGER = 3;
    const TEAM = 4;

    const PERFECT = '/^U\d{7,8}$/';

    private $_password;
    private $_info;
    public $repeat;
    public $adult;
    public $agreement;

    public static function primaryKey() {
        return ['id'];
    }

    public static function statuses() {
        return [
            User::BLOCKED => Yii::t('app', 'Blocked'),
            User::ADMIN => Yii::t('app', 'Admin'),
            User::PLAIN => Yii::t('app', 'Registered'),
            User::MANAGER => Yii::t('app', 'Manager'),
            User::TEAM => Yii::t('app', 'Team')
        ];
    }

    public static $events = [
        'login' => 'Вход',
        'logout' => 'Выход',
        'login_fail' => 'Неудачная попытка входа',
    ];

    public function traceable() {
        return ['status', 'email', 'account'];
    }

    public function url() {
        return ['user/view', 'name' => $this->name];
    }

    public function rules() {
        return [
            ['id', 'integer'],
            [['name', 'email', 'account', 'perfect'], 'required'],
            [['password', 'repeat'], 'required', 'on' => 'signup'],
            ['name', 'string', 'min' => 4, 'max' => 24],
            ['name', 'match', 'pattern' => '/^[a-z][a-z0-9_\-]+$/i', 'on' => 'signup'],
            [['name', 'email'], 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['email', 'email'],
            ['repeat', 'compare', 'compareAttribute' => 'password'],
            ['perfect', 'match', 'pattern' => static::PERFECT, 'message' =>
                Yii::t('app', 'The wallet should looks like U1234567')],
        ];
    }

    public function scenarios() {
        return [
            'default' => ['email'],
            'signup'  => ['name', 'email', 'password', 'repeat', 'perfect', 'ref_name'],
            'admin'   => ['name', 'email',  'account', 'status', 'perfect', 'ref_name'],
        ];
    }

    public function attributeLabels() {
        return [
            'name' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Password'),
            'repeat' => Yii::t('app', 'Repeat'),
            'status' => Yii::t('app', 'Status'),
            'account' => Yii::t('app', 'Account'),
            'perfect' => Yii::t('app', 'Perfect Money wallet'),
            'last_access' => 'Последняя активность',
            'ref_name' => 'Реферал',
        ];
    }

    public function behaviors() {
        return [
            Journal::class
        ];
    }

    public function init() {
        parent::init();
        if (isset(Yii::$app->user)
            && Yii::$app->user instanceof WebUser
            && !Yii::$app->user->getIsGuest()
            && static::ADMIN == Yii::$app->user->identity->status) {
            $this->scenario = 'admin';
        }
    }

    /**
     * @param string $id
     * @return User
     */
    public static function findIdentity($id) {
        return parent::findOne(['id' => $id]);
    }

    public static function findIdentityByAccessToken($token, $type = null) {
        throw new Exception('Not implemented findIdentityByAccessToken');
    }

    public function getId() {
        return $this->id;
    }

    public function getAuthKey() {
        return $this->auth;
    }

    public function validateAuthKey($authKey) {
        return $authKey == $this->auth;
    }

    public function validatePassword($password) {
        return password_verify($password, $this->hash);
    }

    public function getPassword() {
        return $this->_password;
    }

    public function setPassword($value) {
        $this->hash = password_hash($value, PASSWORD_DEFAULT);
        $this->_password = $value;
    }

    public function generateAuthKey() {
        $this->auth = Yii::$app->security->generateRandomString(64);
    }

    public function generateCode() {
        $this->code = Yii::$app->security->generateRandomString(64);
    }

    public function isTeam() {
        return static::TEAM == $this->status || static::ADMIN == $this->status || static::MANAGER == $this->status;
    }

    public function isManager() {
        return static::ADMIN == $this->status || static::MANAGER == $this->status;
    }

    public function isAdmin() {
        return static::ADMIN == $this->status;
    }

    public function __toString() {
        return $this->name;
    }

    public function sendEmail($params)
    {
        $template = Yii::getAlias('@app') . "/views/mail.php";
        return Yii::$app->mailer->compose()
            ->setTo($this->email)
            ->setFrom([Settings::get('common', 'email') => Yii::$app->name])
            ->setSubject($params['subject'])
            ->setHtmlBody(Yii::$app->view->renderFile($template, $params))
            ->send();
    }

    public function canLogin() {
        return Record::find()->andWhere([
            'object_id' => $this->id,
            'event' => 'login_fail'
        ])
            ->andWhere('(NOW() - "time") < interval \'5 minutes\'')
            ->count() < Settings::get('common', 'login_fails');
    }

    /**
     * @return ActiveRecord
     */
    public static function online() {
        return static::find()
            ->andWhere('(NOW() - "last_access") < interval \'15 minutes\'');
    }

    public function getBundle() {
        if (!$this->_info) {
            $this->_info = unserialize(stream_get_contents($this->data));
        }
        return $this->_info;
    }

    public function setBundle($value) {
        $value = empty($value) ? null : serialize($value);
        $this->data = $value;
        $this->_info = $value;
    }

    public function setBundleFromAttributes($names, $restore = false) {
        $bundle = [];
        foreach($names as $name) {
            $bundle[$name] = $this->$name;
            if ($restore) {
                $this->$name = $this->getOldAttribute($name);
            }
        }
        $this->setBundle($bundle);
    }

    public function journalView() {
        return __DIR__ . '/../views/user/journal.php';
    }

    public function getReferral() {
        return $this->hasOne(User::class, ['name' => 'ref_name']);
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\LoginForm;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\helpers\SQL;
use app\models\Settings;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'vip' => ['post'],
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['index', 'view', 'update', 'cabinet'],
                'manager' => ['complete', 'account'],
                'admin' => ['delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => Yii::$app->user->identity->isManager() ? null : Yii::$app->user->identity
        ]);
    }

    public function actionView($name = null) {
        if (!$name && Yii::$app->user->isGuest) {
            throw new InvalidParamException();
        }

        $model = $name ? $this->findModel($name) : Yii::$app->user->identity;
        if (Yii::$app->user->isGuest
            || (!Yii::$app->user->identity->isManager() && Yii::$app->user->identity->name != $model->name)) {
            throw new ForbiddenHttpException();
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail([
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
            }

            if ($model->save()) {
                return $this->redirect(['view', 'name' => $model->name]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup($ref_name = null) {
        $model = new User([
            'scenario' => 'signup'
        ]);
        if (!$ref_name && Yii::$app->session->has('ref_name')) {
            $ref_name = Yii::$app->session->get('ref_name');
        }
        if ($ref_name) {
            $model->ref_name = $ref_name;
            if (!Yii::$app->session->has('ref_name')) {
                Yii::$app->session->set('ref_name', $ref_name);
            }
        }
        if (preg_match(User::PERFECT, $model->name)) {
            $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
        }
        elseif ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->generateAuthKey();
            $model->status = User::PLAIN;
            if ($model->save(false) && Yii::$app->user->login($model)) {
                return $this->redirect(['/user/view']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $model = new LoginForm(['scenario' => Yii::$app->layout]);
        if ('admin' == $model->getScenario()) {
            $model->duration = 60;
        }

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                            }
                            $user->last_access = date('Y-m-d H:i:s');

                            if ('admin' == Yii::$app->layout && !$user->isManager()) {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'You cannot manage site'));
                            }
                            elseif ($user->save() && Yii::$app->user->login($user,
                                    'admin' == Yii::$app->layout && $model->remember ? $model->duration * 60 : 0)) {
                                return $this->redirect('admin' == Yii::$app->layout ? ['/home/statistics'] : ['/user/view']);
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'
                            ])->orderBy(['time' => SORT_DESC])->one();
                            Yii::$app->session->setFlash('error',
                                Yii::t('app', 'You have exceeded the maximum number of login attempts, you will be able to enter after {time}', [
                                    'time' => $record->time
                                ]));
                        }
                    }
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['home/index']);
    }

    public function actionEmail($code) {
        /** @var User $user */
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
            $user = User::findOne(['name' => $code]);
        }
        else {
            $user = preg_match('|^[\w\-_]{64}$|', $code) ? User::findOne(['code' => $code]) : null;
        }
        if ($user) {
            $bundle = $user->getBundle();
            $message = empty($user->hash) ? 'Congratulations. You have successfully activated!' : 'Your email changed!';
            foreach($bundle as $name => $value) {
                $user->$name = $value;
            }
            $user->code = null;
            $user->setBundle(null);
            if ($user->save()) {
                Yii::$app->session->addFlash('success', Yii::t('app', $message));
                Yii::$app->user->login($user);
                return $this->redirect(['user/view']);
            }
            else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
            }
        }
        else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Invalid code'));
        }
        return $this->redirect(['home/index']);
    }

    public function actionPassword($code = null, $name = null) {
        /** @var User $user */
        $message = null;

views/user/_form.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use app\widgets\AjaxComplete;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */

echo Ext::stamp();

$form = ActiveForm::begin();

if ($model->ref_name && $model->isNewRecord): ?>
    <div class="form-group">
        <?= Yii::t('app', 'Referral') . ': ' . $model->ref_name; ?>
    </div>
    <?= Html::activeHiddenInput($model, 'ref_name') ?>
<?php endif;
if ($model->isNewRecord) {
    echo Html::activeTextInput($model, 'name', ['placeholder' => 'ЛОГИН']);
}

if ('signup' == $model->scenario):
    echo Html::activeTextInput($model, 'email', ['placeholder' => 'E-MAIL']);
    echo Html::activePasswordInput($model, 'password', ['placeholder' => 'ПАРОЛЬ']);
    echo Html::activePasswordInput($model, 'repeat', ['placeholder' => 'ПОВТОРИТЕ ПАРОЛЬ']);
    echo Html::activeTextInput($model, 'perfect', ['placeholder' => 'КОШЕЛЕК PM']);
endif;

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'account');
    echo $form->field($model, 'perfect');
    echo $form->field($model, 'status')->dropDownList(User::statuses());
    echo $form->field($model, 'ref_name')->widget(AjaxComplete::class, [
        'route' => ['/user/complete']
    ]);
}

?>
<div class="buttons">
    <?php

    if (Yii::$app->user->isGuest) {
        echo Html::submitButton('Регистрация');
    }
    else {
        echo Html::submitButton(Yii::t('app', $model->isNewRecord ? 'Create' : 'Update'));
    }

    ActiveForm::end();
    ?>
</div>

views/user/_search.php
<?php
/**
 * @link http://zenothing.com/
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'hash') ?>

    <?= $form->field($model, 'auth') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/account.php
<?php
/**
 * @link http://zenothing.com/
 */
use yii\helpers\Html;

?>
<div class="account">
    <h1><?= Yii::t('app', 'Accounts') ?></h1>
    <table class="table">
        <?php
        foreach($model as $key => $value) {
            echo Html::tag('tr',
                Html::tag('td', Yii::t('app', $key)) .
                Html::tag('td', $value)
            );
        }
        ?>
    </table>
</div>

views/user/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::$app->user->isGuest ? 'Регистрация' : Yii::t('app', 'Create User');
?>
<h1 class="blue-border"><?= Html::encode($this->title) ?></h1>
<div class="user-create userform">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>
<img src="/images/shadow.png" />

views/user/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */

if (isset($_GET['ref_name'])) {
    $this->title = 'Партнеры пользовател ' . $_GET['ref_name'];
}
else {
    $this->title = Yii::t('app', 'Users');
}

$columns = [
    [
        'attribute' => 'name',
        'format' => 'html',
        'value' => function(User $model) {
            return Html::a($model->name, ['view', 'name' => $model->name]);
        }
    ],
    'account',
    [
        'attribute' => 'ref_name',
        'format' => 'html',
        'value' => function(User $model) {
            return $model->ref_name ? Html::a($model->ref_name, ['index', 'ref_name' => $model->ref_name]) : null;
        }
    ],
    [
        'attribute' => 'last_access',
        'format' => 'datetime',
        'contentOptions' => [
            'class' => 'moment'
        ]
    ]
];

if (!Yii::$app->user->getIsGuest() && Yii::$app->user->identity->isAdmin()) {
    $columns[] = 'email:email';
    $columns[] = [
        'format' => 'html',
        'contentOptions' => ['class' => 'action'],
        'value' => function($model) {
            return implode(' ', [
                Html::a('', ['update', 'name' => $model->name], ['class' => 'glyphicon glyphicon-pencil']),
//                Html::a('', ['delete', 'id' => $model->id], ['class' => 'glyphicon glyphicon-trash'])
            ]);
        }
    ];
}
?>
<div class="user-index">
    <div>
        <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?php
            if (Yii::$app->user->identity->isAdmin()) {
                echo Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']);
            }
            ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => $columns,
        ]); ?>
    </div>
</div>

views/user/journal.php
<?php
/**
 * @link http://zenothing.com/
*/

/**
 * @var app\models\Record $record
 */

use app\models\User;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Yii::t('app', 'Status') . ': ' . User::statuses()[$info['status']];
}
elseif (isset($info['account'])) {
    echo Yii::t('app', 'Account') . ': ' . $info['account'];
}
else {
    $key = key($info);
    echo "$key: " . $info[$key];
}

views/user/panel.php
<?php
/** @var \app\models\User $model */
use app\models\Settings;
use app\modules\bank\models\Bonus;
use yii\helpers\Html;
use yii\helpers\Url;

if (!Yii::$app->user->getIsGuest()):
    $items = [
        Html::a(Yii::t('app', 'Opened Deposits'),
            ['/bank/node/index', 'user' => $model->name], ['class' => 'btn btn-primary']),
        Html::a(Yii::t('app', 'Income'),
            ['/bank/income/index', 'user' => $model->name], ['class' => 'btn btn-primary'])
    ];

    if (Bonus::count($model->name) > 0) {
        $items[] = Html::tag('li', Html::a('Реферальные начисления',
            ['/bank/bonus/index', 'user' => $model->name], ['class' => 'btn btn-primary']));
    }

    if ($model->name == Yii::$app->user->identity->name || Yii::$app->user->identity->isAdmin()) {
        $items[] = Html::tag('li', Html::a(Yii::t('app', 'Change Password'),
            ['/user/password', 'name' => $model->name], ['class' => 'btn btn-warning']));
    }

    if (Yii::$app->user->identity->isManager()) {
        $items[] = Html::tag('li', Html::a(Yii::t('app', 'Update'),
            ['/user/update', 'name' => $model->name], ['class' => 'btn btn-primary']));
    }

    if ($model->name == Yii::$app->user->identity->name) {
        $items[] = Html::tag('li', Html::a(Yii::t('app', 'Sponsors'),
            ['index', 'ref_name' => $model->name], ['class' => 'btn btn-primary']));
    }

    if (Yii::$app->user->identity->isAdmin()) {
        if (empty($model->hash)) {
            $items[] = Html::tag('li', Html::a(Yii::t('app', 'Activate'), ['/user/email', 'code' => $model->name], ['class' => 'btn btn-primary']));
        }
        $items[] = Html::tag('li', Html::a(Yii::t('app', 'Delete'), ['/user/delete', 'name' => $model->name
        ], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]));
    }
    elseif ($model->name == Yii::$app->user->identity->name) {
        echo ' ';
        $items[] = Html::tag('li', implode("\n", [
            Html::beginForm('https://perfectmoney.is/api/step1.asp', 'POST'),
            Html::hiddenInput('PAYEE_ACCOUNT', Settings::get('perfect', 'wallet')),
            Html::textInput('PAYMENT_AMOUNT', Settings::get('deposit', 'min'), ['size' => 3]),
            Html::hiddenInput('PAYEE_NAME', Yii::$app->name),
            Html::hiddenInput('PAYMENT_UNITS', 'USD'),
            Html::hiddenInput('PAYMENT_URL', Url::to(['/invoice/invoice/success'], true)),
            Html::hiddenInput('NOPAYMENT_URL', Url::to(['/invoice/invoice/fail'], true)),
            Html::hiddenInput('BAGGAGE_FIELDS', 'USER_NAME'),
            Html::hiddenInput('USER_NAME', Yii::$app->user->identity->name),
            Html::button(Yii::t('app', 'Pay'), [
                'name' => 'PAYMENT_METHOD',
                'type' => 'submit',
                'class' => 'btn btn-primary'
            ]),
            Html::endForm()
        ]));
    }


    echo Html::tag('div', Html::ul($items, ['encode' => false]), ['id' => 'user-panel']);
endif;

views/user/request.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\widgets\Ext;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Request for password recovery');

?>
<div class="user-password">
    <?= Ext::stamp() ?>
    <h1><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/view.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\Settings;
use app\models\User;
use app\modules\bank\controllers\IncomeController;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */


$this->title = $model->name;
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
}

$columns = [
    'name',
    'email:email',
    'last_access:datetime',
    [
        'attribute' => 'account',
        'format' => 'html',
        'value' => Html::tag('span', $model->account) . ' ' . ($model->account > 0 ? Html::a(Yii::t('app', 'Withdraw'),
                ['invoice/invoice/create', 'amount' => (int) $model->account, 'scenario' => 'withdraw'],
                ['class' => 'btn btn-success btn-xs']) : '')
    ],
    'perfect',
    'ref_name'
];

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    $columns[] = [
        'attribute' => 'status',
        'value' => User::statuses()[$model->status]
    ];
}

?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    require 'panel.php';
    ?>

    <div>
        <?php if (Settings::get('common', 'referral') > 0):
            $referral = Url::to(['/user/signup', 'ref_name' => $model->name], true);
            ?>
            <div>
                <?php
                echo Html::a(Yii::t('app', 'Referral Link'), $referral, ['class' => 'form-label']);
                ?>

                <input class="form-control" value="<?= Url::to($referral, true); ?>">
            </div>
        <?php endif ?>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => $columns,
        ]) ?>
    </div>

    <?php
    $params = IncomeController::index($model->name);
    $params['user'] = $model;
    echo Yii::$app->view->render('@app/modules/bank/views/income/index', $params);
    ?>
</div>